name: Test Backend / CI & CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        
    steps:
    - uses: actions/checkout@v3
          
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install, and test
      run: |
        npm install
        npm test
      env:
        CI: true

  build-push-gcr:
    name: Build and push to GCP
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: backend-image
      PROJECT_ID: devops-test-project-352613
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: google-github-actions/setup-gcloud@v0
        with: 
          service-account-key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credintials: true
          
      - name: build docker image
        run: docker build -t $IMAGE_NAME:latest .
      
      - name: configure docker client
        run: |- 
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-west2-docker.pkg.dev --quiet
      
 #     - name: push docker image to container registry (GCR)
 #       env: 
 #         GIT_TAG: v0.1.0
 #         
 #       run: |-
 #         docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
 #         docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:GIT_TAG
 #         docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
 #         docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:GIT_TAG
          
      - name: push docker image to Artifact registry
        env: 
          GIT_TAG: v0.1.0
          
        run: |-
          docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:GIT_TAG
          docker push us-west2-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest
          docker push us-west2-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:GIT_TAG
